<?php


function getExampleRecipes(): array {
    return [
        [
            'id' => 1,
            'title' => 'Spaghetti Carbonara',
            'description' => 'Klassisches italienisches Nudelgericht mit Speck, Ei und Parmesan.',
            'time_minutes' => 25,
            'servings' => 4,
            'image_url' => 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800',
            'tags' => [
                'meal'     => ['Mittagessen','Abendessen'],
                'course'   => ['Hauptgericht'],
                'cuisine'  => ['Italienisch'],
                'level'    => ['Einfach'],
                'specials' => ['Proteinreich'],
            ],
            'ingredients' => [
                ['quantity' => '400', 'unit' => 'g', 'name' => 'Spaghetti'],
                ['quantity' => '200', 'unit' => 'g', 'name' => 'Speck'],
                ['quantity' => '4', 'unit' => 'Stk', 'name' => 'Eier'],
                ['quantity' => '100', 'unit' => 'g', 'name' => 'Parmesan'],
                ['quantity' => '1', 'unit' => 'Prise', 'name' => 'Salz'],
                ['quantity' => '1', 'unit' => 'Prise', 'name' => 'Pfeffer'],
            ],
            'steps' => "Spaghetti nach Packungsanweisung kochen.\nSpeck braten.\nEier mit Parmesan verquirlen.\nNudeln mit Speck mischen.\nEi-Mischung unterrühren.\nWürzen.",
            'user' => 'anna',
        ],
        [
            'id' => 2,
            'title' => 'Thai-Curry',
            'description' => 'Würziges rotes Curry mit Gemüse und Kokosmilch.',
            'time_minutes' => 35,
            'servings' => 4,
            'image_url' => 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800',
            'tags' => [
                'meal'     => ['Mittagessen','Abendessen'],
                'course'   => ['Hauptgericht'],
                'cuisine'  => ['Asiatisch'],
                'level'    => ['Mittel'],
                'specials' => ['Vegetarisch'],
            ],
            'ingredients' => [
                ['quantity' => '400', 'unit' => 'ml', 'name' => 'Kokosmilch'],
                ['quantity' => '2', 'unit' => 'EL', 'name' => 'Rote Currypaste'],
                ['quantity' => '1', 'unit' => 'Stk', 'name' => 'Paprika'],
                ['quantity' => '1', 'unit' => 'Stk', 'name' => 'Zucchini'],
                ['quantity' => '200', 'unit' => 'g', 'name' => 'Reis'],
                ['quantity' => '1', 'unit' => 'EL', 'name' => 'Sojasoße'],
            ],
            'steps' => "Reis kochen.\nGemüse schneiden.\nPaste anbraten.\nKokosmilch zugeben.\nGemüse köcheln.\nAbschmecken.",
            'user' => 'bob',
        ],
        [
            'id' => 3,
            'title' => 'Schokokuchen',
            'description' => 'Saftiger Schokoladenkuchen für Naschkatzen.',
            'time_minutes' => 60,
            'servings' => 8,
            'image_url' => 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800',
            'tags' => [
                'meal'     => ['Abendessen'],
                'course'   => ['Dessert'],
                'cuisine'  => ['Französisch'],
                'level'    => ['Einfach'],
                'specials' => ['Vegetarisch'],
            ],
            'ingredients' => [
                ['quantity' => '200', 'unit' => 'g', 'name' => 'Mehl'],
                ['quantity' => '200', 'unit' => 'g', 'name' => 'Zucker'],
                ['quantity' => '100', 'unit' => 'g', 'name' => 'Kakao'],
                ['quantity' => '3', 'unit' => 'Stk', 'name' => 'Eier'],
                ['quantity' => '150', 'unit' => 'ml', 'name' => 'Öl'],
                ['quantity' => '200', 'unit' => 'ml', 'name' => 'Milch'],
                ['quantity' => '1', 'unit' => 'Pck', 'name' => 'Backpulver'],
            ],
            'steps' => "Ofen vorheizen.\nTrockene Zutaten mischen.\nFlüssige zugeben.\nBacken.\nAuskühlen.",
            'user' => 'anna',
        ],
        [
            'id' => 4,
            'title' => 'Caesar Salad',
            'description' => 'Knackiger Salat mit Hähnchen und Parmesan.',
            'time_minutes' => 20,
            'servings' => 2,
            'image_url' => 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=800',
            'tags' => [
                'meal'     => ['Mittagessen','Abendessen'],
                'course'   => ['Salat'],
                'cuisine'  => ['Mediterran'],
                'level'    => ['Einfach'],
                'specials' => ['Proteinreich'],
            ],
            'ingredients' => [
                ['quantity' => '2', 'unit' => 'Stk', 'name' => 'Hähnchenbrustfilet'],
                ['quantity' => '1', 'unit' => 'Stk', 'name' => 'Römersalat'],
                ['quantity' => '50', 'unit' => 'g', 'name' => 'Parmesan'],
                ['quantity' => '100', 'unit' => 'ml', 'name' => 'Caesar Dressing'],
                ['quantity' => '50', 'unit' => 'g', 'name' => 'Croutons'],
            ],
            'steps' => "Hähnchen braten.\nSalat vorbereiten.\nMischen.\nParmesan hinzu.",
            'user' => 'charlie',
        ],
        [
            'id' => 5,
            'title' => 'Pancakes',
            'description' => 'Fluffige amerikanische Pfannkuchen.',
            'time_minutes' => 15,
            'servings' => 4,
            'image_url' => 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800',
            'tags' => [
                'meal'     => ['Frühstück'],
                'course'   => ['Dessert','Snack'],
                'cuisine'  => [],
                'level'    => ['Einfach'],
                'specials' => ['Vegetarisch','Schnelle Küche'],
            ],
            'ingredients' => [
                ['quantity' => '200', 'unit' => 'g', 'name' => 'Mehl'],
                ['quantity' => '2', 'unit' => 'Stk', 'name' => 'Eier'],
                ['quantity' => '250', 'unit' => 'ml', 'name' => 'Milch'],
                ['quantity' => '2', 'unit' => 'EL', 'name' => 'Zucker'],
                ['quantity' => '1', 'unit' => 'TL', 'name' => 'Backpulver'],
                ['quantity' => '30', 'unit' => 'g', 'name' => 'Butter'],
            ],
            'steps' => "Teig rühren.\nBacken.\nServieren.",
            'user' => 'anna',
        ],
        [
            'id' => 6,
            'title' => 'Chili con Carne',
            'description' => 'Herzhafter Bohneneintopf mit Hackfleisch.',
            'time_minutes' => 60,
            'servings' => 6,
            'image_url' => 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=800',
            'tags' => [
                'meal'     => ['Mittagessen','Abendessen'],
                'course'   => ['Hauptgericht'],
                'cuisine'  => ['Mexikanisch'],
                'level'    => ['Mittel'],
                'specials' => ['Proteinreich'],
            ],
            'ingredients' => [
                ['quantity' => '500', 'unit' => 'g', 'name' => 'Rinderhack'],
                ['quantity' => '2', 'unit' => 'Dose', 'name' => 'Kidneybohnen'],
                ['quantity' => '400', 'unit' => 'g', 'name' => 'Tomaten (gehackt)'],
                ['quantity' => '2', 'unit' => 'Stk', 'name' => 'Zwiebeln'],
                ['quantity' => '2', 'unit' => 'Zehe', 'name' => 'Knoblauch'],
                ['quantity' => '2', 'unit' => 'TL', 'name' => 'Chilipulver'],
                ['quantity' => '1', 'unit' => 'TL', 'name' => 'Kreuzkümmel'],
            ],
            'steps' => "Zwiebeln, Hack, Bohnen, würzen, köcheln.",
            'user' => 'bob',
        ],
        [
            'id' => 7,
            'title' => 'Griechischer Salat',
            'description' => 'Frischer Salat mit Feta und Oliven.',
            'time_minutes' => 10,
            'servings' => 4,
            'image_url' => 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800',
            'tags' => [
                'meal'     => ['Mittagessen','Abendessen'],
                'course'   => ['Salat'],
                'cuisine'  => ['Mediterran'],
                'level'    => ['Einfach'],
                'specials' => ['Vegetarisch','Schnelle Küche'],
            ],
            'ingredients' => [
                ['quantity' => '3', 'unit' => 'Stk', 'name' => 'Tomaten'],
                ['quantity' => '1', 'unit' => 'Stk', 'name' => 'Gurke'],
                ['quantity' => '200', 'unit' => 'g', 'name' => 'Feta'],
                ['quantity' => '100', 'unit' => 'g', 'name' => 'Oliven'],
                ['quantity' => '1', 'unit' => 'Stk', 'name' => 'Rote Zwiebel'],
                ['quantity' => '3', 'unit' => 'EL', 'name' => 'Olivenöl'],
                ['quantity' => '1', 'unit' => 'TL', 'name' => 'Oregano'],
            ],
            'steps' => "Schneiden.\nMischen.\nWürzen.",
            'user' => 'charlie',
        ],
        [
            'id' => 8,
            'title' => 'Lasagne',
            'description' => 'Klassische italienische Lasagne mit Bolognese.',
            'time_minutes' => 90,
            'servings' => 6,
            'image_url' => 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800',
            'tags' => [
                'meal'     => ['Mittagessen','Abendessen'],
                'course'   => ['Hauptgericht'],
                'cuisine'  => ['Italienisch'],
                'level'    => ['Mittel'],
                'specials' => ['Proteinreich'],
            ],
            'ingredients' => [
                ['quantity' => '500', 'unit' => 'g', 'name' => 'Hackfleisch'],
                ['quantity' => '12', 'unit' => 'Stk', 'name' => 'Lasagneplatten'],
                ['quantity' => '500', 'unit' => 'ml', 'name' => 'Bechamelsauce'],
                ['quantity' => '400', 'unit' => 'g', 'name' => 'Tomaten (gehackt)'],
                ['quantity' => '1', 'unit' => 'Stk', 'name' => 'Zwiebel'],
                ['quantity' => '200', 'unit' => 'g', 'name' => 'Mozzarella'],
                ['quantity' => '50', 'unit' => 'g', 'name' => 'Parmesan'],
            ],
            'steps' => "Bolognese.\nSchichten.\nBacken.",
            'user' => 'anna',
        ],
        [
            'id' => 9,
            'title' => 'Pad Thai',
            'description' => 'Thailändische gebratene Reisnudeln.',
            'time_minutes' => 30,
            'servings' => 4,
            'image_url' => 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=800',
            'tags' => [
                'meal'     => ['Mittagessen','Abendessen'],
                'course'   => ['Hauptgericht'],
                'cuisine'  => ['Asiatisch'],
                'level'    => ['Mittel'],
                'specials' => ['Schnelle Küche'],
            ],
            'ingredients' => [
                ['quantity' => '300', 'unit' => 'g', 'name' => 'Reisnudeln'],
                ['quantity' => '200', 'unit' => 'g', 'name' => 'Garnelen'],
                ['quantity' => '2', 'unit' => 'Stk', 'name' => 'Eier'],
                ['quantity' => '100', 'unit' => 'g', 'name' => 'Sojasprossen'],
                ['quantity' => '3', 'unit' => 'EL', 'name' => 'Fischsauce'],
                ['quantity' => '2', 'unit' => 'EL', 'name' => 'Tamarindenpaste'],
                ['quantity' => '50', 'unit' => 'g', 'name' => 'Erdnüsse'],
            ],
            'steps' => "Einweichen.\nBraten.\nMischen.",
            'user' => 'bob',
        ],
        [
            'id' => 10,
            'title' => 'Ratatouille',
            'description' => 'Französischer Gemüseeintopf.',
            'time_minutes' => 50,
            'servings' => 4,
            'image_url' => 'https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=800',
            'tags' => [
                'meal'     => ['Mittagessen','Abendessen'],
                'course'   => ['Hauptgericht'],
                'cuisine'  => ['Französisch'],
                'level'    => ['Mittel'],
                'specials' => ['Vegetarisch','Vegan'],
            ],
            'ingredients' => [
                ['quantity' => '2', 'unit' => 'Stk', 'name' => 'Auberginen'],
                ['quantity' => '2', 'unit' => 'Stk', 'name' => 'Zucchini'],
                ['quantity' => '3', 'unit' => 'Stk', 'name' => 'Paprika'],
                ['quantity' => '400', 'unit' => 'g', 'name' => 'Tomaten'],
                ['quantity' => '1', 'unit' => 'Stk', 'name' => 'Zwiebel'],
                ['quantity' => '3', 'unit' => 'Zehe', 'name' => 'Knoblauch'],
                ['quantity' => '4', 'unit' => 'EL', 'name' => 'Olivenöl'],
            ],
            'steps' => "Schichten.\nBacken.",
            'user' => 'charlie',
        ],
        [
            'id' => 11,
            'title' => 'Tiramisu',
            'description' => 'Italienisches Dessert mit Mascarpone.',
            'time_minutes' => 30,
            'servings' => 6,
            'image_url' => 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800',
            'tags' => [
                'meal'     => ['Abendessen'],
                'course'   => ['Dessert'],
                'cuisine'  => ['Italienisch'],
                'level'    => ['Einfach'],
                'specials' => ['Vegetarisch'],
            ],
            'ingredients' => [
                ['quantity' => '500', 'unit' => 'g', 'name' => 'Mascarpone'],
                ['quantity' => '200', 'unit' => 'g', 'name' => 'Löffelbiskuits'],
                ['quantity' => '4', 'unit' => 'Stk', 'name' => 'Eier'],
                ['quantity' => '200', 'unit' => 'ml', 'name' => 'Espresso'],
                ['quantity' => '80', 'unit' => 'g', 'name' => 'Zucker'],
                ['quantity' => '2', 'unit' => 'EL', 'name' => 'Kakao'],
            ],
            'steps' => "Schichten.\nKühlen.\nBestäuben.",
            'user' => 'anna',
        ],
        [
            'id' => 12,
            'title' => 'Quiche Lorraine',
            'description' => 'Französischer Speckkuchen.',
            'time_minutes' => 60,
            'servings' => 6,
            'image_url' => 'https://images.unsplash.com/photo-1476124369491-b79886d293eb?w=800',
            'tags' => [
                'meal'     => ['Mittagessen','Abendessen'],
                'course'   => ['Hauptgericht'],
                'cuisine'  => ['Französisch'],
                'level'    => ['Mittel'],
                'specials' => ['Proteinreich'],
            ],
            'ingredients' => [
                ['quantity' => '1', 'unit' => 'Stk', 'name' => 'Mürbeteig'],
                ['quantity' => '200', 'unit' => 'g', 'name' => 'Speck'],
                ['quantity' => '3', 'unit' => 'Stk', 'name' => 'Eier'],
                ['quantity' => '200', 'unit' => 'ml', 'name' => 'Sahne'],
                ['quantity' => '100', 'unit' => 'g', 'name' => 'Käse'],
                ['quantity' => '1', 'unit' => 'Prise', 'name' => 'Muskatnuss'],
            ],
            'steps' => "Teig.\nFüllen.\nBacken.",
            'user' => 'bob',
        ],
        [
            'id' => 13,
            'title' => 'Falafel',
            'description' => 'Orientalische Kichererbsenbällchen.',
            'time_minutes' => 45,
            'servings' => 4,
            'image_url' => 'https://images.unsplash.com/photo-1593504049359-74330189a345?w=800',
            'tags' => [
                'meal'     => ['Mittagessen','Abendessen'],
                'course'   => ['Snack','Vorspeise'],
                'cuisine'  => ['Orientalisch'],
                'level'    => ['Mittel'],
                'specials' => ['Vegetarisch','Vegan'],
            ],
            'ingredients' => [
                ['quantity' => '400', 'unit' => 'g', 'name' => 'Kichererbsen (getrocknet)'],
                ['quantity' => '1', 'unit' => 'Stk', 'name' => 'Zwiebel'],
                ['quantity' => '2', 'unit' => 'Zehe', 'name' => 'Knoblauch'],
                ['quantity' => '1', 'unit' => 'TL', 'name' => 'Kreuzkümmel'],
                ['quantity' => '1', 'unit' => 'TL', 'name' => 'Koriander'],
                ['quantity' => '3', 'unit' => 'EL', 'name' => 'Petersilie'],
                ['quantity' => '3', 'unit' => 'EL', 'name' => 'Mehl'],
            ],
            'steps' => "Einweichen.\nMasse.\nFormen.\nFrittieren.",
            'user' => 'charlie',
        ],
        [
            'id' => 14,
            'title' => 'Beef Wellington',
            'description' => 'Rinderfilet im Blätterteig.',
            'time_minutes' => 90,
            'servings' => 4,
            'image_url' => 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800',
            'tags' => [
                'meal'     => ['Abendessen'],
                'course'   => ['Hauptgericht'],
                'cuisine'  => [],
                'level'    => ['Anspruchsvoll'],
                'specials' => ['Proteinreich'],
            ],
            'ingredients' => [
                ['quantity' => '800', 'unit' => 'g', 'name' => 'Rinderfilet'],
                ['quantity' => '1', 'unit' => 'Pkg', 'name' => 'Blätterteig'],
                ['quantity' => '200', 'unit' => 'g', 'name' => 'Champignons'],
                ['quantity' => '100', 'unit' => 'g', 'name' => 'Leberpastete'],
                ['quantity' => '4', 'unit' => 'Scheiben', 'name' => 'Parmaschinken'],
                ['quantity' => '1', 'unit' => 'Stk', 'name' => 'Eigelb'],
            ],
            'steps' => "Anbraten.\nUmmanteln.\nBacken.",
            'user' => 'anna',
        ],
        [
            'id' => 15,
            'title' => 'Guacamole',
            'description' => 'Mexikanischer Avocado-Dip.',
            'time_minutes' => 10,
            'servings' => 4,
            'image_url' => 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800',
            'tags' => [
                'meal'     => ['Mittagessen','Abendessen'],
                'course'   => ['Snack','Vorspeise'],
                'cuisine'  => ['Mexikanisch'],
                'level'    => ['Einfach'],
                'specials' => ['Vegetarisch','Vegan','Schnelle Küche'],
            ],
            'ingredients' => [
                ['quantity' => '3', 'unit' => 'Stk', 'name' => 'Avocados'],
                ['quantity' => '1', 'unit' => 'Stk', 'name' => 'Limette'],
                ['quantity' => '1', 'unit' => 'Stk', 'name' => 'Tomate'],
                ['quantity' => '1', 'unit' => 'Stk', 'name' => 'Zwiebel'],
                ['quantity' => '1', 'unit' => 'Zehe', 'name' => 'Knoblauch'],
                ['quantity' => '1', 'unit' => 'Prise', 'name' => 'Salz'],
            ],
            'steps' => "Zerdrücken.\nMischen.\nServieren.",
            'user' => 'bob',
        ],
        [
            'id' => 16,
            'title' => 'Pho',
            'description' => 'Vietnamesische Nudelsuppe.',
            'time_minutes' => 120,
            'servings' => 4,
            'image_url' => 'https://images.unsplash.com/photo-1591814468924-caf88d1232e1?w=800',
            'tags' => [
                'meal'     => ['Mittagessen','Abendessen'],
                'course'   => ['Suppe','Hauptgericht'],
                'cuisine'  => ['Asiatisch'],
                'level'    => ['Mittel'],
                'specials' => ['Proteinreich'],
            ],
            'ingredients' => [
                ['quantity' => '500', 'unit' => 'g', 'name' => 'Rinderknochen'],
                ['quantity' => '200', 'unit' => 'g', 'name' => 'Reisnudeln'],
                ['quantity' => '200', 'unit' => 'g', 'name' => 'Rindfleisch'],
                ['quantity' => '1', 'unit' => 'Stk', 'name' => 'Ingwer'],
                ['quantity' => '2', 'unit' => 'Stk', 'name' => 'Sternanis'],
                ['quantity' => '1', 'unit' => 'Stange', 'name' => 'Zimt'],
                ['quantity' => '3', 'unit' => 'EL', 'name' => 'Fischsauce'],
            ],
            'steps' => "Brühe.\nNudeln.\nAnrichten.",
            'user' => 'charlie',
        ],
        [
            'id' => 17,
            'title' => 'Paella',
            'description' => 'Spanisches Reisgericht mit Meeresfrüchten.',
            'time_minutes' => 50,
            'servings' => 6,
            'image_url' => 'https://images.unsplash.com/photo-1534080564583-6be75777b70a?w=800',
            'tags' => [
                'meal'     => ['Mittagessen','Abendessen'],
                'course'   => ['Hauptgericht'],
                'cuisine'  => ['Mediterran'],
                'level'    => ['Mittel'],
                'specials' => ['Proteinreich'],
            ],
            'ingredients' => [
                ['quantity' => '400', 'unit' => 'g', 'name' => 'Paella-Reis'],
                ['quantity' => '300', 'unit' => 'g', 'name' => 'Meeresfrüchte-Mix'],
                ['quantity' => '200', 'unit' => 'g', 'name' => 'Hähnchen'],
                ['quantity' => '1', 'unit' => 'Prise', 'name' => 'Safran'],
                ['quantity' => '1', 'unit' => 'Stk', 'name' => 'Paprika'],
                ['quantity' => '800', 'unit' => 'ml', 'name' => 'Hühnerbrühe'],
                ['quantity' => '100', 'unit' => 'g', 'name' => 'Erbsen'],
            ],
            'steps' => "Anbraten.\nKöcheln.\nGarziehen.",
            'user' => 'anna',
        ],
        [
            'id' => 18,
            'title' => 'Hummus',
            'description' => 'Cremiger Kichererbsen-Dip.',
            'time_minutes' => 15,
            'servings' => 6,
            'image_url' => 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800',
            'tags' => [
                'meal'     => ['Mittagessen','Abendessen'],
                'course'   => ['Snack','Vorspeise'],
                'cuisine'  => ['Orientalisch'],
                'level'    => ['Einfach'],
                'specials' => ['Vegetarisch','Vegan','Schnelle Küche'],
            ],
            'ingredients' => [
                ['quantity' => '400', 'unit' => 'g', 'name' => 'Kichererbsen (Dose)'],
                ['quantity' => '3', 'unit' => 'EL', 'name' => 'Tahini'],
                ['quantity' => '2', 'unit' => 'Zehe', 'name' => 'Knoblauch'],
                ['quantity' => '1', 'unit' => 'Stk', 'name' => 'Zitrone'],
                ['quantity' => '4', 'unit' => 'EL', 'name' => 'Olivenöl'],
                ['quantity' => '1', 'unit' => 'TL', 'name' => 'Kreuzkümmel'],
            ],
            'steps' => "Pürieren.\nAbschmecken.",
            'user' => 'bob',
        ],
        [
            'id' => 19,
            'title' => 'Risotto',
            'description' => 'Cremiges italienisches Reisgericht.',
            'time_minutes' => 35,
            'servings' => 4,
            'image_url' => 'https://images.unsplash.com/photo-1476124369491-b79886d293eb?w=800',
            'tags' => [
                'meal'     => ['Mittagessen','Abendessen'],
                'course'   => ['Hauptgericht'],
                'cuisine'  => ['Italienisch'],
                'level'    => ['Mittel'],
                'specials' => ['Vegetarisch'],
            ],
            'ingredients' => [
                ['quantity' => '300', 'unit' => 'g', 'name' => 'Risotto-Reis'],
                ['quantity' => '1', 'unit' => 'l', 'name' => 'Gemüsebrühe'],
                ['quantity' => '100', 'unit' => 'ml', 'name' => 'Weißwein'],
                ['quantity' => '50', 'unit' => 'g', 'name' => 'Parmesan'],
                ['quantity' => '1', 'unit' => 'Stk', 'name' => 'Zwiebel'],
                ['quantity' => '50', 'unit' => 'g', 'name' => 'Butter'],
            ],
            'steps' => "Rühren.\nKöcheln.\nVerfeinern.",
            'user' => 'charlie',
        ],
        [
            'id' => 20,
            'title' => 'Shakshuka',
            'description' => 'Israelisches Eiergericht in Tomatensauce.',
            'time_minutes' => 30,
            'servings' => 4,
            'image_url' => 'https://images.unsplash.com/photo-1587740896339-96a76170508d?w=800',
            'tags' => [
                'meal'     => ['Frühstück'],
                'course'   => ['Hauptgericht'],
                'cuisine'  => ['Orientalisch'],
                'level'    => ['Einfach'],
                'specials' => ['Vegetarisch','Proteinreich'],
            ],
            'ingredients' => [
                ['quantity' => '6', 'unit' => 'Stk', 'name' => 'Eier'],
                ['quantity' => '400', 'unit' => 'g', 'name' => 'Tomaten (gehackt)'],
                ['quantity' => '2', 'unit' => 'Stk', 'name' => 'Paprika'],
                ['quantity' => '1', 'unit' => 'TL', 'name' => 'Kreuzkümmel'],
                ['quantity' => '1', 'unit' => 'Stk', 'name' => 'Zwiebel'],
                ['quantity' => '2', 'unit' => 'Zehe', 'name' => 'Knoblauch'],
                ['quantity' => '1', 'unit' => 'TL', 'name' => 'Paprikapulver'],
            ],
            'steps' => "Gemüse.\nSauce.\nEier stocken.",
            'user' => 'anna',
        ],
        [
            'id' => 21,
            'title' => 'Crème Brûlée',
            'description' => 'Französisches Dessert mit karamellisierter Kruste.',
            'time_minutes' => 90,
            'servings' => 4,
            'image_url' => 'https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc?w=800',
            'tags' => [
                'meal'     => ['Abendessen'],
                'course'   => ['Dessert'],
                'cuisine'  => ['Französisch'],
                'level'    => ['Anspruchsvoll'],
                'specials' => ['Vegetarisch'],
            ],
            'ingredients' => [
                ['quantity' => '500', 'unit' => 'ml', 'name' => 'Sahne'],
                ['quantity' => '5', 'unit' => 'Stk', 'name' => 'Eigelb'],
                ['quantity' => '100', 'unit' => 'g', 'name' => 'Zucker'],
                ['quantity' => '1', 'unit' => 'Stk', 'name' => 'Vanilleschote'],
                ['quantity' => '4', 'unit' => 'EL', 'name' => 'Brauner Zucker'],
            ],
            'steps' => "Erhitzen.\nBacken.\nKaramellisieren.",
            'user' => 'bob',
        ],
    ];
}